workflows:
  # ============================================================
  # WORKFLOW 1: GENERATE KEYSTORE (ONE-TIME SETUP ONLY)
  # ============================================================
  # ⚠️  SECURITY WARNING: This workflow is for ONE-TIME keystore generation only.
  #
  # PREREQUISITES:
  # - You already have the "watomagic_keystore" group with:
  #   * KEYSTORE_PASSWORD (secure text)
  #   * KEY_ALIAS (secure text)
  #   * KEY_PASSWORD (secure text)
  #
  # SETUP INSTRUCTIONS:
  # 1. Trigger this workflow ONCE manually
  # 2. Download the .keystore file from artifacts
  # 3. SECURITY CLEANUP (CRITICAL):
  #    a) Delete this build from Codemagic build history
  #    b) Delete the artifact from Codemagic
  # 4. Upload keystore to Codemagic:
  #    - Go to watomagic_keystore group
  #    - Add KEYSTORE (file, secure) = upload the downloaded .keystore file
  # 5. DELETE THIS ENTIRE WORKFLOW from codemagic.yaml (lines 1-108)
  # 6. Commit the updated codemagic.yaml without this workflow
  #
  # After cleanup, only "android-release" workflow should remain.
  # ============================================================

  generate-keystore:
    name: "🔐 Generate Keystore (ONE-TIME SETUP)"
    max_build_duration: 10
    instance_type: mac_mini_m2

    environment:
      java: 17
      # Use the same group that contains the passwords
      # The KEYSTORE file variable is not needed yet (we're generating it)
      # but the passwords and alias are already there
      groups:
        - watomagic_keystore

    scripts:
      - name: Debug environment variables
        script: |
          echo "🔍 DEBUG: Checking environment variables..."
          echo ""
          echo "All environment variables (filtered for security):"
          env | grep -E "(KEYSTORE|KEY_|ALIAS)" | sed 's/=.*/=[MASKED]/' || echo "No matching variables found"
          echo ""
          echo "Checking specific variables:"
          echo "KEYSTORE_PASSWORD is set: $([ -n "$KEYSTORE_PASSWORD" ] && echo "YES" || echo "NO")"
          echo "KEY_PASSWORD is set: $([ -n "$KEY_PASSWORD" ] && echo "YES" || echo "NO")"
          echo "KEY_ALIAS is set: $([ -n "$KEY_ALIAS" ] && echo "YES" || echo "NO")"
          echo ""

      - name: Generate Keystore
        script: |
          echo "🔐 Generating Android keystore..."
          echo ""
          echo "⚠️  SECURITY NOTICE:"
          echo "   This keystore will be valid for 27 years (10000 days)"
          echo "   Google Play requires certificates valid until at least Oct 22, 2033"
          echo "   This keystore will be valid until approximately 2052"
          echo ""

          # Validate that variables from watomagic_keystore group are available
          if [ -z "$KEYSTORE_PASSWORD" ]; then
            echo "❌ ERROR: KEYSTORE_PASSWORD not set"
            echo "   Ensure watomagic_keystore group contains KEYSTORE_PASSWORD"
            echo ""
            echo "DEBUG INFO:"
            echo "- Check that the group 'watomagic_keystore' exists in CodeMagic"
            echo "- Check that it's referenced in the workflow's android_signing section"
            echo "- Check that KEYSTORE_PASSWORD variable exists in the group"
            echo "- Check that the variable is NOT marked as 'Secure' for this test"
            exit 1
          fi

          if [ -z "$KEY_PASSWORD" ]; then
            echo "❌ ERROR: KEY_PASSWORD not set"
            echo "   Ensure watomagic_keystore group contains KEY_PASSWORD"
            exit 1
          fi

          if [ -z "$KEY_ALIAS" ]; then
            echo "❌ ERROR: KEY_ALIAS not set"
            echo "   Ensure watomagic_keystore group contains KEY_ALIAS"
            exit 1
          fi

          echo "✅ All required variables found from watomagic_keystore group"
          echo "   - KEYSTORE_PASSWORD: [MASKED]"
          echo "   - KEY_PASSWORD: [MASKED]"
          echo "   - KEY_ALIAS: $KEY_ALIAS"
          echo ""

          # Generate keystore
          keytool -genkey -v \
            -storetype JKS \
            -keystore watomagic-release.keystore \
            -alias "$KEY_ALIAS" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=Parishod, OU=Development, O=Gryphsoft, L=Buenos Aires, ST=Buenos Aires, C=AR"

          echo ""
          echo "✅ Keystore generated successfully"

      - name: Verify Keystore
        script: |
          echo "🔍 Verifying keystore..."
          echo ""

          keytool -list -v -keystore watomagic-release.keystore -storepass "$KEYSTORE_PASSWORD"

          echo ""
          echo "📦 Keystore file details:"
          ls -lh watomagic-release.keystore

          echo ""
          echo "✅ Keystore validation complete"
          echo ""
          echo "=============================================="
          echo "🔒 CRITICAL NEXT STEPS (SECURITY):"
          echo "=============================================="
          echo ""
          echo "1. Download watomagic-release.keystore from artifacts"
          echo "2. Save it securely in a password manager or secure vault"
          echo "3. DELETE this build from Codemagic build history"
          echo "4. DELETE the artifact from Codemagic"
          echo "5. Upload keystore to watomagic_keystore group:"
          echo "   - Go to Codemagic → Watomagic → Environment variables"
          echo "   - Edit watomagic_keystore group"
          echo "   - Add KEYSTORE (file, secure) = upload .keystore file"
          echo "6. DELETE this entire workflow from codemagic.yaml (lines 1-108)"
          echo "7. Commit and push the updated codemagic.yaml"
          echo "8. Test the android-release workflow with signing"
          echo ""
          echo "⚠️  If you lose the keystore, you CANNOT update the app!"
          echo "=============================================="

    artifacts:
      - watomagic-release.keystore

  # ============================================================
  # WORKFLOW 2: ANDROID RELEASE BUILD (SIGNED APK)
  # ============================================================
  android-release:
    name: "Watomagic Android Release Build (Signed APK)"
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 17
      # Android signing identity configured in CodeMagic UI
      # (Code signing identities → Android → "watomagic_keystore")
      android_signing:
        - watomagic_keystore
      vars:
        # Package name for the Default flavor (F-Droid variant)
        PACKAGE_NAME: "com.parishod.watomagic"
        # Base version code for CI/CD builds (incremented with BUILD_NUMBER)
        BASE_VERSION_CODE: 10000

    # Cache Gradle dependencies for faster builds
    cache:
      cache_paths:
        - ~/.gradle/caches
        - .gradle

    scripts:
      # ============================================================
      # SCRIPT 1: Setup Android SDK location
      # ============================================================
      - name: Setup local.properties
        script: |
          echo "✅ Setting up Android SDK location..."
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
          cat local.properties
          echo "✅ local.properties configured"

      # ============================================================
      # SCRIPT 2: Generate Gradle Wrapper (ensure specific version)
      # ============================================================
      - name: Generate Gradle Wrapper
        script: |
          echo "✅ Verifying Gradle wrapper..."
          if [ ! -f "gradlew" ]; then
            echo "⚠️  Gradle wrapper not found, generating..."
            gradle wrapper --gradle-version 8.12 --distribution-type all
          else
            echo "✅ Gradle wrapper exists"
          fi

          # Verify wrapper version
          echo "📦 Gradle wrapper properties:"
          cat gradle/wrapper/gradle-wrapper.properties | grep distributionUrl

      # ============================================================
      # SCRIPT 3: Fix Gradle wrapper permissions
      # ============================================================
      - name: Fix gradlew permissions
        script: |
          echo "✅ Setting execute permissions on gradlew..."
          chmod +x gradlew
          ls -la gradlew
          echo "✅ Permissions updated"

      # ============================================================
      # SCRIPT 4: Verify Java and Gradle environment
      # ============================================================
      - name: Verify Java and Gradle environment
        script: |
          echo "☕ Java version:"
          java -version
          echo ""
          echo "📍 JAVA_HOME: $JAVA_HOME"
          echo "📍 ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo ""
          echo "🔧 Gradle version:"
          ./gradlew --version --no-daemon
          echo ""
          echo "📋 Gradle projects:"
          ./gradlew projects --no-daemon

      # ============================================================
      # SCRIPT 5: Verify Signing Configuration
      # ============================================================
      - name: Verify signing configuration
        script: |
          echo "🔐 Verifying signing configuration..."
          echo ""

          # Check that all signing variables from android_signing identity are set
          # CodeMagic injects these with CM_ prefix from "Code signing identities"
          if [ -z "$CM_KEYSTORE_PATH" ]; then
            echo "❌ ERROR: CM_KEYSTORE_PATH not set"
            echo "   Configure 'Watomagic' in Code signing identities → Android"
            exit 1
          fi

          if [ -z "$CM_KEYSTORE_PASSWORD" ]; then
            echo "❌ ERROR: CM_KEYSTORE_PASSWORD not set"
            exit 1
          fi

          if [ -z "$CM_KEY_ALIAS" ]; then
            echo "❌ ERROR: CM_KEY_ALIAS not set"
            exit 1
          fi

          if [ -z "$CM_KEY_PASSWORD" ]; then
            echo "❌ ERROR: CM_KEY_PASSWORD not set"
            exit 1
          fi

          # Verify keystore file exists
          if [ ! -f "$CM_KEYSTORE_PATH" ]; then
            echo "❌ ERROR: Keystore file not found at $CM_KEYSTORE_PATH"
            exit 1
          fi

          echo "✅ Keystore file exists: $CM_KEYSTORE_PATH"
          ls -lh "$CM_KEYSTORE_PATH"

          echo ""
          echo "✅ All signing variables configured correctly (from Code signing identity)"

      # ============================================================
      # SCRIPT 6: Verify Import Statements
      # ============================================================
      - name: Verify import statements
        script: |
          echo "🔍 Verifying import statements in project..."
          echo ""
          
          # Make script executable
          chmod +x scripts/check_imports.sh
          
          # Run import verification
          ./scripts/check_imports.sh
          
          echo "✅ Import verification completed"

      # ============================================================
      # SCRIPT 7: Run Unit Tests (non-blocking)
      # ============================================================
      - name: Run unit tests
        script: |
          echo "🧪 Running unit tests..."
          echo "⚠️  Tests are non-blocking - failures will be logged but won't stop the build"

          # Run tests, continue even if they fail
          ./gradlew test --no-daemon --stacktrace || {
            echo "❌ Unit tests failed, but continuing build process..."
            echo "📋 Check test reports in Codemagic logs for details"
          }

          # Show test results if available
          if [ -d "app/build/reports/tests" ]; then
            echo "📊 Test reports generated:"
            find app/build/reports/tests -name "index.html" -type f
          fi

          echo "✅ Unit test execution completed (check logs for results)"

      # ============================================================
      # SCRIPT 8: Run Lint Checks (non-blocking)
      # ============================================================
      - name: Run lint checks
        script: |
          echo "🔍 Running Android lint checks..."
          echo "⚠️  Lint is non-blocking - issues will be logged but won't stop the build"

          # Run lint, continue even if it fails
          ./gradlew lintDefaultRelease --no-daemon --stacktrace || {
            echo "⚠️  Lint found issues, but continuing build process..."
            echo "📋 Check lint reports in Codemagic logs for details"
          }

          # Show lint results if available
          if [ -f "app/build/reports/lint-results-DefaultRelease.html" ]; then
            echo "📊 Lint report generated: app/build/reports/lint-results-DefaultRelease.html"
          fi

          echo "✅ Lint check completed (check logs for results)"

      # ============================================================
      # SCRIPT 9: Build Android Release APK (SIGNED)
      # ============================================================
      - name: Build Android Release APK (SIGNED)
        script: |
          echo "🏗️  Building SIGNED Android Release APK (Default flavor)..."

          # Calculate dynamic version code: BASE_VERSION_CODE + BUILD_NUMBER
          VERSION_CODE=$((BASE_VERSION_CODE + BUILD_NUMBER))
          VERSION_NAME="1.$BUILD_NUMBER"

          echo "📦 Version configuration:"
          echo "   - Version Code: $VERSION_CODE"
          echo "   - Version Name: $VERSION_NAME"
          echo "   - Build Number: $BUILD_NUMBER"
          echo ""

          # Ensure Android SDK path is available for Gradle
          SDK_PATH="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/Users/builder/Library/Android/sdk}}"
          if [ ! -d "$SDK_PATH" ]; then
            echo "❌ Android SDK not found at '$SDK_PATH'. Set ANDROID_SDK_ROOT or ANDROID_HOME."
            exit 1
          fi

          echo "sdk.dir=${SDK_PATH}" > local.properties
          echo "🛠️  Using Android SDK at: $SDK_PATH"
          echo ""

          echo "🔐 Signing configuration:"
          echo "   - Keystore: $CM_KEYSTORE_PATH"
          echo "   - Key Alias: $CM_KEY_ALIAS"
          echo ""

          echo "🚀 Starting Gradle build with signing..."
          ./gradlew assembleDefaultRelease \
            -PversionCode=$VERSION_CODE \
            -PversionName=$VERSION_NAME \
            -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD \
            --no-daemon \
            --parallel \
            --stacktrace \
            --info

          echo "✅ Gradle build command completed"

      # ============================================================
      # SCRIPT 10: Validate APK Build Artifacts
      # ============================================================
      - name: Validate APK artifacts
        script: |
          echo "🔍 Validating APK build artifacts..."

          APK_PATH="app/build/outputs/apk/Default/release/app-Default-release.apk"

          if [ -f "$APK_PATH" ]; then
            echo "✅ SIGNED APK generated successfully!"
            echo ""
            echo "📦 APK Details:"
            echo "   - Path: $APK_PATH"

            # Get APK size
            if command -v stat > /dev/null 2>&1; then
              # macOS stat command
              APK_SIZE=$(stat -f%z "$APK_PATH" 2>/dev/null || stat -c%s "$APK_PATH" 2>/dev/null)
              APK_SIZE_MB=$(echo "scale=2; $APK_SIZE / 1048576" | bc)
              echo "   - Size: $APK_SIZE bytes ($APK_SIZE_MB MB)"
            else
              ls -lh "$APK_PATH"
            fi

            # Verify APK is not empty
            if [ "$APK_SIZE" -gt 1000000 ]; then
              echo "   - Status: Valid (size > 1MB)"
            else
              echo "   - ⚠️  Warning: APK size seems too small"
            fi

            echo ""
            echo "🔐 Verifying APK signature..."
            apksigner verify --verbose "$APK_PATH" || {
              echo "⚠️  APK signature verification failed"
              echo "This might be expected on some build environments"
            }

            echo ""
            echo "✅ APK validation successful"
            echo "📥 APK will be available as downloadable artifact in Codemagic"
          else
            echo "❌ ERROR: APK not found at expected path!"
            echo "   Expected: $APK_PATH"
            echo ""
            echo "📋 Searching for APK files:"
            find app/build/outputs -name "*.apk" -type f || echo "No APK files found"
            exit 1
          fi

      # ============================================================
      # SCRIPT 11: Display Build Summary
      # ============================================================
      - name: Build summary
        script: |
          echo "======================================"
          echo "📱 WATOMAGIC BUILD SUMMARY"
          echo "======================================"
          echo ""
          echo "✅ Build Type: Release (SIGNED)"
          echo "✅ Flavor: Default (F-Droid variant)"
          echo "✅ Application ID: com.parishod.watomagic"
          echo "✅ Version Code: $((BASE_VERSION_CODE + BUILD_NUMBER))"
          echo "✅ Version Name: 1.$BUILD_NUMBER"
          echo "✅ Signing: ENABLED"
          echo ""
          echo "📦 Artifacts:"
          echo "   - APK: app-Default-release.apk (SIGNED)"
          echo "   - Location: app/build/outputs/apk/Default/release/"
          echo ""
          echo "🎯 Next Steps:"
          echo "   1. Download the SIGNED APK from Codemagic artifacts"
          echo "   2. Upload to Google Play Console (Internal/Alpha/Beta testing)"
          echo "   3. Install on test devices (adb install -r <apk>)"
          echo ""
          echo "======================================"

    # ============================================================
    # ARTIFACTS: Files to save and make downloadable
    # ============================================================
    artifacts:
      - app/build/outputs/apk/Default/release/*.apk
      - app/build/reports/tests/**/*
      - app/build/reports/lint-*.html

    # ============================================================
    # PUBLISHING: Email notifications
    # ============================================================
    publishing:
      email:
        recipients:
          - devs@gryphsoft.com
        notify:
          success: true
          failure: true
